package com.chally.dao;

import com.chally.vo.Challenge;
import com.chally.vo.ChallengeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChallengeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table challenge
     *
     * @mbg.generated Mon Jul 29 23:36:37 KST 2024
     */
    long countByExample(ChallengeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table challenge
     *
     * @mbg.generated Mon Jul 29 23:36:37 KST 2024
     */
    int deleteByExample(ChallengeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table challenge
     *
     * @mbg.generated Mon Jul 29 23:36:37 KST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table challenge
     *
     * @mbg.generated Mon Jul 29 23:36:37 KST 2024
     */
    int insert(Challenge row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table challenge
     *
     * @mbg.generated Mon Jul 29 23:36:37 KST 2024
     */
    int insertSelective(Challenge row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table challenge
     *
     * @mbg.generated Mon Jul 29 23:36:37 KST 2024
     */
    List<Challenge> selectByExampleWithBLOBs(ChallengeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table challenge
     *
     * @mbg.generated Mon Jul 29 23:36:37 KST 2024
     */
    List<Challenge> selectByExample(ChallengeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table challenge
     *
     * @mbg.generated Mon Jul 29 23:36:37 KST 2024
     */
    Challenge selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table challenge
     *
     * @mbg.generated Mon Jul 29 23:36:37 KST 2024
     */
    int updateByExampleSelective(@Param("row") Challenge row, @Param("example") ChallengeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table challenge
     *
     * @mbg.generated Mon Jul 29 23:36:37 KST 2024
     */
    int updateByExampleWithBLOBs(@Param("row") Challenge row, @Param("example") ChallengeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table challenge
     *
     * @mbg.generated Mon Jul 29 23:36:37 KST 2024
     */
    int updateByExample(@Param("row") Challenge row, @Param("example") ChallengeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table challenge
     *
     * @mbg.generated Mon Jul 29 23:36:37 KST 2024
     */
    int updateByPrimaryKeySelective(Challenge row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table challenge
     *
     * @mbg.generated Mon Jul 29 23:36:37 KST 2024
     */
    int updateByPrimaryKeyWithBLOBs(Challenge row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table challenge
     *
     * @mbg.generated Mon Jul 29 23:36:37 KST 2024
     */
    int updateByPrimaryKey(Challenge row);
}