package com.chally.dao;

import com.chally.vo.SpringSession;
import com.chally.vo.SpringSessionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SpringSessionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_session
     *
     * @mbg.generated Fri Jul 12 21:59:27 KST 2024
     */
    long countByExample(SpringSessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_session
     *
     * @mbg.generated Fri Jul 12 21:59:27 KST 2024
     */
    int deleteByExample(SpringSessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_session
     *
     * @mbg.generated Fri Jul 12 21:59:27 KST 2024
     */
    int deleteByPrimaryKey(String primaryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_session
     *
     * @mbg.generated Fri Jul 12 21:59:27 KST 2024
     */
    int insert(SpringSession row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_session
     *
     * @mbg.generated Fri Jul 12 21:59:27 KST 2024
     */
    int insertSelective(SpringSession row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_session
     *
     * @mbg.generated Fri Jul 12 21:59:27 KST 2024
     */
    List<SpringSession> selectByExample(SpringSessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_session
     *
     * @mbg.generated Fri Jul 12 21:59:27 KST 2024
     */
    SpringSession selectByPrimaryKey(String primaryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_session
     *
     * @mbg.generated Fri Jul 12 21:59:27 KST 2024
     */
    int updateByExampleSelective(@Param("row") SpringSession row, @Param("example") SpringSessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_session
     *
     * @mbg.generated Fri Jul 12 21:59:27 KST 2024
     */
    int updateByExample(@Param("row") SpringSession row, @Param("example") SpringSessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_session
     *
     * @mbg.generated Fri Jul 12 21:59:27 KST 2024
     */
    int updateByPrimaryKeySelective(SpringSession row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spring_session
     *
     * @mbg.generated Fri Jul 12 21:59:27 KST 2024
     */
    int updateByPrimaryKey(SpringSession row);
}