package com.chally.vo;

import java.util.Date;

public class Challenge {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column challenge.id
     *
     * @mbg.generated Mon Jul 29 23:36:37 KST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column challenge.TITLE
     *
     * @mbg.generated Mon Jul 29 23:36:37 KST 2024
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column challenge.MIN_JOIN
     *
     * @mbg.generated Mon Jul 29 23:36:37 KST 2024
     */
    private Integer minJoin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column challenge.MAX_JOIN
     *
     * @mbg.generated Mon Jul 29 23:36:37 KST 2024
     */
    private Integer maxJoin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column challenge.START_DT
     *
     * @mbg.generated Mon Jul 29 23:36:37 KST 2024
     */
    private Date startDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column challenge.END_DT
     *
     * @mbg.generated Mon Jul 29 23:36:37 KST 2024
     */
    private Date endDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column challenge.DELETE_AT
     *
     * @mbg.generated Mon Jul 29 23:36:37 KST 2024
     */
    private String deleteAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column challenge.REGIST_DT
     *
     * @mbg.generated Mon Jul 29 23:36:37 KST 2024
     */
    private Date registDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column challenge.UPDT_DT
     *
     * @mbg.generated Mon Jul 29 23:36:37 KST 2024
     */
    private Date updtDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column challenge.CONTENT
     *
     * @mbg.generated Mon Jul 29 23:36:37 KST 2024
     */
    private byte[] content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column challenge.id
     *
     * @return the value of challenge.id
     *
     * @mbg.generated Mon Jul 29 23:36:37 KST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column challenge.id
     *
     * @param id the value for challenge.id
     *
     * @mbg.generated Mon Jul 29 23:36:37 KST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column challenge.TITLE
     *
     * @return the value of challenge.TITLE
     *
     * @mbg.generated Mon Jul 29 23:36:37 KST 2024
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column challenge.TITLE
     *
     * @param title the value for challenge.TITLE
     *
     * @mbg.generated Mon Jul 29 23:36:37 KST 2024
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column challenge.MIN_JOIN
     *
     * @return the value of challenge.MIN_JOIN
     *
     * @mbg.generated Mon Jul 29 23:36:37 KST 2024
     */
    public Integer getMinJoin() {
        return minJoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column challenge.MIN_JOIN
     *
     * @param minJoin the value for challenge.MIN_JOIN
     *
     * @mbg.generated Mon Jul 29 23:36:37 KST 2024
     */
    public void setMinJoin(Integer minJoin) {
        this.minJoin = minJoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column challenge.MAX_JOIN
     *
     * @return the value of challenge.MAX_JOIN
     *
     * @mbg.generated Mon Jul 29 23:36:37 KST 2024
     */
    public Integer getMaxJoin() {
        return maxJoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column challenge.MAX_JOIN
     *
     * @param maxJoin the value for challenge.MAX_JOIN
     *
     * @mbg.generated Mon Jul 29 23:36:37 KST 2024
     */
    public void setMaxJoin(Integer maxJoin) {
        this.maxJoin = maxJoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column challenge.START_DT
     *
     * @return the value of challenge.START_DT
     *
     * @mbg.generated Mon Jul 29 23:36:37 KST 2024
     */
    public Date getStartDt() {
        return startDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column challenge.START_DT
     *
     * @param startDt the value for challenge.START_DT
     *
     * @mbg.generated Mon Jul 29 23:36:37 KST 2024
     */
    public void setStartDt(Date startDt) {
        this.startDt = startDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column challenge.END_DT
     *
     * @return the value of challenge.END_DT
     *
     * @mbg.generated Mon Jul 29 23:36:37 KST 2024
     */
    public Date getEndDt() {
        return endDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column challenge.END_DT
     *
     * @param endDt the value for challenge.END_DT
     *
     * @mbg.generated Mon Jul 29 23:36:37 KST 2024
     */
    public void setEndDt(Date endDt) {
        this.endDt = endDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column challenge.DELETE_AT
     *
     * @return the value of challenge.DELETE_AT
     *
     * @mbg.generated Mon Jul 29 23:36:37 KST 2024
     */
    public String getDeleteAt() {
        return deleteAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column challenge.DELETE_AT
     *
     * @param deleteAt the value for challenge.DELETE_AT
     *
     * @mbg.generated Mon Jul 29 23:36:37 KST 2024
     */
    public void setDeleteAt(String deleteAt) {
        this.deleteAt = deleteAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column challenge.REGIST_DT
     *
     * @return the value of challenge.REGIST_DT
     *
     * @mbg.generated Mon Jul 29 23:36:37 KST 2024
     */
    public Date getRegistDt() {
        return registDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column challenge.REGIST_DT
     *
     * @param registDt the value for challenge.REGIST_DT
     *
     * @mbg.generated Mon Jul 29 23:36:37 KST 2024
     */
    public void setRegistDt(Date registDt) {
        this.registDt = registDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column challenge.UPDT_DT
     *
     * @return the value of challenge.UPDT_DT
     *
     * @mbg.generated Mon Jul 29 23:36:37 KST 2024
     */
    public Date getUpdtDt() {
        return updtDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column challenge.UPDT_DT
     *
     * @param updtDt the value for challenge.UPDT_DT
     *
     * @mbg.generated Mon Jul 29 23:36:37 KST 2024
     */
    public void setUpdtDt(Date updtDt) {
        this.updtDt = updtDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column challenge.CONTENT
     *
     * @return the value of challenge.CONTENT
     *
     * @mbg.generated Mon Jul 29 23:36:37 KST 2024
     */
    public byte[] getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column challenge.CONTENT
     *
     * @param content the value for challenge.CONTENT
     *
     * @mbg.generated Mon Jul 29 23:36:37 KST 2024
     */
    public void setContent(byte[] content) {
        this.content = content;
    }
}