package com.chally.vo;

public class SpringSession {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_session.PRIMARY_ID
     *
     * @mbg.generated Fri Jul 12 21:59:27 KST 2024
     */
    private String primaryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_session.SESSION_ID
     *
     * @mbg.generated Fri Jul 12 21:59:27 KST 2024
     */
    private String sessionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_session.CREATION_TIME
     *
     * @mbg.generated Fri Jul 12 21:59:27 KST 2024
     */
    private Long creationTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_session.LAST_ACCESS_TIME
     *
     * @mbg.generated Fri Jul 12 21:59:27 KST 2024
     */
    private Long lastAccessTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_session.MAX_INACTIVE_INTERVAL
     *
     * @mbg.generated Fri Jul 12 21:59:27 KST 2024
     */
    private Integer maxInactiveInterval;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_session.EXPIRY_TIME
     *
     * @mbg.generated Fri Jul 12 21:59:27 KST 2024
     */
    private Long expiryTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spring_session.PRINCIPAL_NAME
     *
     * @mbg.generated Fri Jul 12 21:59:27 KST 2024
     */
    private String principalName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_session.PRIMARY_ID
     *
     * @return the value of spring_session.PRIMARY_ID
     *
     * @mbg.generated Fri Jul 12 21:59:27 KST 2024
     */
    public String getPrimaryId() {
        return primaryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_session.PRIMARY_ID
     *
     * @param primaryId the value for spring_session.PRIMARY_ID
     *
     * @mbg.generated Fri Jul 12 21:59:27 KST 2024
     */
    public void setPrimaryId(String primaryId) {
        this.primaryId = primaryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_session.SESSION_ID
     *
     * @return the value of spring_session.SESSION_ID
     *
     * @mbg.generated Fri Jul 12 21:59:27 KST 2024
     */
    public String getSessionId() {
        return sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_session.SESSION_ID
     *
     * @param sessionId the value for spring_session.SESSION_ID
     *
     * @mbg.generated Fri Jul 12 21:59:27 KST 2024
     */
    public void setSessionId(String sessionId) {
        this.sessionId = sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_session.CREATION_TIME
     *
     * @return the value of spring_session.CREATION_TIME
     *
     * @mbg.generated Fri Jul 12 21:59:27 KST 2024
     */
    public Long getCreationTime() {
        return creationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_session.CREATION_TIME
     *
     * @param creationTime the value for spring_session.CREATION_TIME
     *
     * @mbg.generated Fri Jul 12 21:59:27 KST 2024
     */
    public void setCreationTime(Long creationTime) {
        this.creationTime = creationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_session.LAST_ACCESS_TIME
     *
     * @return the value of spring_session.LAST_ACCESS_TIME
     *
     * @mbg.generated Fri Jul 12 21:59:27 KST 2024
     */
    public Long getLastAccessTime() {
        return lastAccessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_session.LAST_ACCESS_TIME
     *
     * @param lastAccessTime the value for spring_session.LAST_ACCESS_TIME
     *
     * @mbg.generated Fri Jul 12 21:59:27 KST 2024
     */
    public void setLastAccessTime(Long lastAccessTime) {
        this.lastAccessTime = lastAccessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_session.MAX_INACTIVE_INTERVAL
     *
     * @return the value of spring_session.MAX_INACTIVE_INTERVAL
     *
     * @mbg.generated Fri Jul 12 21:59:27 KST 2024
     */
    public Integer getMaxInactiveInterval() {
        return maxInactiveInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_session.MAX_INACTIVE_INTERVAL
     *
     * @param maxInactiveInterval the value for spring_session.MAX_INACTIVE_INTERVAL
     *
     * @mbg.generated Fri Jul 12 21:59:27 KST 2024
     */
    public void setMaxInactiveInterval(Integer maxInactiveInterval) {
        this.maxInactiveInterval = maxInactiveInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_session.EXPIRY_TIME
     *
     * @return the value of spring_session.EXPIRY_TIME
     *
     * @mbg.generated Fri Jul 12 21:59:27 KST 2024
     */
    public Long getExpiryTime() {
        return expiryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_session.EXPIRY_TIME
     *
     * @param expiryTime the value for spring_session.EXPIRY_TIME
     *
     * @mbg.generated Fri Jul 12 21:59:27 KST 2024
     */
    public void setExpiryTime(Long expiryTime) {
        this.expiryTime = expiryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spring_session.PRINCIPAL_NAME
     *
     * @return the value of spring_session.PRINCIPAL_NAME
     *
     * @mbg.generated Fri Jul 12 21:59:27 KST 2024
     */
    public String getPrincipalName() {
        return principalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spring_session.PRINCIPAL_NAME
     *
     * @param principalName the value for spring_session.PRINCIPAL_NAME
     *
     * @mbg.generated Fri Jul 12 21:59:27 KST 2024
     */
    public void setPrincipalName(String principalName) {
        this.principalName = principalName;
    }
}