package com.chally.vo;

public class TestChally {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test_chally.TEST_SEQ
	 * @mbg.generated  Fri Jul 12 22:36:13 KST 2024
	 */
	private String testSeq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test_chally.TEST_TITLE
	 * @mbg.generated  Fri Jul 12 22:36:13 KST 2024
	 */
	private String testTitle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test_chally.TEST_PLAIN
	 * @mbg.generated  Fri Jul 12 22:36:13 KST 2024
	 */
	private String testPlain;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test_chally.TEST_SEQ
	 * @return  the value of test_chally.TEST_SEQ
	 * @mbg.generated  Fri Jul 12 22:36:13 KST 2024
	 */
	public String getTestSeq() {
		return testSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test_chally.TEST_SEQ
	 * @param testSeq  the value for test_chally.TEST_SEQ
	 * @mbg.generated  Fri Jul 12 22:36:13 KST 2024
	 */
	public void setTestSeq(String testSeq) {
		this.testSeq = testSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test_chally.TEST_TITLE
	 * @return  the value of test_chally.TEST_TITLE
	 * @mbg.generated  Fri Jul 12 22:36:13 KST 2024
	 */
	public String getTestTitle() {
		return testTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test_chally.TEST_TITLE
	 * @param testTitle  the value for test_chally.TEST_TITLE
	 * @mbg.generated  Fri Jul 12 22:36:13 KST 2024
	 */
	public void setTestTitle(String testTitle) {
		this.testTitle = testTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test_chally.TEST_PLAIN
	 * @return  the value of test_chally.TEST_PLAIN
	 * @mbg.generated  Fri Jul 12 22:36:13 KST 2024
	 */
	public String getTestPlain() {
		return testPlain;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test_chally.TEST_PLAIN
	 * @param testPlain  the value for test_chally.TEST_PLAIN
	 * @mbg.generated  Fri Jul 12 22:36:13 KST 2024
	 */
	public void setTestPlain(String testPlain) {
		this.testPlain = testPlain;
	}
}