package com.chally.vo;

import java.util.ArrayList;
import java.util.List;

public class TestChallyExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table test_chally
	 * @mbg.generated  Fri Jul 12 22:36:13 KST 2024
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table test_chally
	 * @mbg.generated  Fri Jul 12 22:36:13 KST 2024
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table test_chally
	 * @mbg.generated  Fri Jul 12 22:36:13 KST 2024
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test_chally
	 * @mbg.generated  Fri Jul 12 22:36:13 KST 2024
	 */
	public TestChallyExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test_chally
	 * @mbg.generated  Fri Jul 12 22:36:13 KST 2024
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test_chally
	 * @mbg.generated  Fri Jul 12 22:36:13 KST 2024
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test_chally
	 * @mbg.generated  Fri Jul 12 22:36:13 KST 2024
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test_chally
	 * @mbg.generated  Fri Jul 12 22:36:13 KST 2024
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test_chally
	 * @mbg.generated  Fri Jul 12 22:36:13 KST 2024
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test_chally
	 * @mbg.generated  Fri Jul 12 22:36:13 KST 2024
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test_chally
	 * @mbg.generated  Fri Jul 12 22:36:13 KST 2024
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test_chally
	 * @mbg.generated  Fri Jul 12 22:36:13 KST 2024
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test_chally
	 * @mbg.generated  Fri Jul 12 22:36:13 KST 2024
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test_chally
	 * @mbg.generated  Fri Jul 12 22:36:13 KST 2024
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table test_chally
	 * @mbg.generated  Fri Jul 12 22:36:13 KST 2024
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andTestSeqIsNull() {
			addCriterion("TEST_SEQ is null");
			return (Criteria) this;
		}

		public Criteria andTestSeqIsNotNull() {
			addCriterion("TEST_SEQ is not null");
			return (Criteria) this;
		}

		public Criteria andTestSeqEqualTo(String value) {
			addCriterion("TEST_SEQ =", value, "testSeq");
			return (Criteria) this;
		}

		public Criteria andTestSeqNotEqualTo(String value) {
			addCriterion("TEST_SEQ <>", value, "testSeq");
			return (Criteria) this;
		}

		public Criteria andTestSeqGreaterThan(String value) {
			addCriterion("TEST_SEQ >", value, "testSeq");
			return (Criteria) this;
		}

		public Criteria andTestSeqGreaterThanOrEqualTo(String value) {
			addCriterion("TEST_SEQ >=", value, "testSeq");
			return (Criteria) this;
		}

		public Criteria andTestSeqLessThan(String value) {
			addCriterion("TEST_SEQ <", value, "testSeq");
			return (Criteria) this;
		}

		public Criteria andTestSeqLessThanOrEqualTo(String value) {
			addCriterion("TEST_SEQ <=", value, "testSeq");
			return (Criteria) this;
		}

		public Criteria andTestSeqLike(String value) {
			addCriterion("TEST_SEQ like", value, "testSeq");
			return (Criteria) this;
		}

		public Criteria andTestSeqNotLike(String value) {
			addCriterion("TEST_SEQ not like", value, "testSeq");
			return (Criteria) this;
		}

		public Criteria andTestSeqIn(List<String> values) {
			addCriterion("TEST_SEQ in", values, "testSeq");
			return (Criteria) this;
		}

		public Criteria andTestSeqNotIn(List<String> values) {
			addCriterion("TEST_SEQ not in", values, "testSeq");
			return (Criteria) this;
		}

		public Criteria andTestSeqBetween(String value1, String value2) {
			addCriterion("TEST_SEQ between", value1, value2, "testSeq");
			return (Criteria) this;
		}

		public Criteria andTestSeqNotBetween(String value1, String value2) {
			addCriterion("TEST_SEQ not between", value1, value2, "testSeq");
			return (Criteria) this;
		}

		public Criteria andTestTitleIsNull() {
			addCriterion("TEST_TITLE is null");
			return (Criteria) this;
		}

		public Criteria andTestTitleIsNotNull() {
			addCriterion("TEST_TITLE is not null");
			return (Criteria) this;
		}

		public Criteria andTestTitleEqualTo(String value) {
			addCriterion("TEST_TITLE =", value, "testTitle");
			return (Criteria) this;
		}

		public Criteria andTestTitleNotEqualTo(String value) {
			addCriterion("TEST_TITLE <>", value, "testTitle");
			return (Criteria) this;
		}

		public Criteria andTestTitleGreaterThan(String value) {
			addCriterion("TEST_TITLE >", value, "testTitle");
			return (Criteria) this;
		}

		public Criteria andTestTitleGreaterThanOrEqualTo(String value) {
			addCriterion("TEST_TITLE >=", value, "testTitle");
			return (Criteria) this;
		}

		public Criteria andTestTitleLessThan(String value) {
			addCriterion("TEST_TITLE <", value, "testTitle");
			return (Criteria) this;
		}

		public Criteria andTestTitleLessThanOrEqualTo(String value) {
			addCriterion("TEST_TITLE <=", value, "testTitle");
			return (Criteria) this;
		}

		public Criteria andTestTitleLike(String value) {
			addCriterion("TEST_TITLE like", value, "testTitle");
			return (Criteria) this;
		}

		public Criteria andTestTitleNotLike(String value) {
			addCriterion("TEST_TITLE not like", value, "testTitle");
			return (Criteria) this;
		}

		public Criteria andTestTitleIn(List<String> values) {
			addCriterion("TEST_TITLE in", values, "testTitle");
			return (Criteria) this;
		}

		public Criteria andTestTitleNotIn(List<String> values) {
			addCriterion("TEST_TITLE not in", values, "testTitle");
			return (Criteria) this;
		}

		public Criteria andTestTitleBetween(String value1, String value2) {
			addCriterion("TEST_TITLE between", value1, value2, "testTitle");
			return (Criteria) this;
		}

		public Criteria andTestTitleNotBetween(String value1, String value2) {
			addCriterion("TEST_TITLE not between", value1, value2, "testTitle");
			return (Criteria) this;
		}

		public Criteria andTestPlainIsNull() {
			addCriterion("TEST_PLAIN is null");
			return (Criteria) this;
		}

		public Criteria andTestPlainIsNotNull() {
			addCriterion("TEST_PLAIN is not null");
			return (Criteria) this;
		}

		public Criteria andTestPlainEqualTo(String value) {
			addCriterion("TEST_PLAIN =", value, "testPlain");
			return (Criteria) this;
		}

		public Criteria andTestPlainNotEqualTo(String value) {
			addCriterion("TEST_PLAIN <>", value, "testPlain");
			return (Criteria) this;
		}

		public Criteria andTestPlainGreaterThan(String value) {
			addCriterion("TEST_PLAIN >", value, "testPlain");
			return (Criteria) this;
		}

		public Criteria andTestPlainGreaterThanOrEqualTo(String value) {
			addCriterion("TEST_PLAIN >=", value, "testPlain");
			return (Criteria) this;
		}

		public Criteria andTestPlainLessThan(String value) {
			addCriterion("TEST_PLAIN <", value, "testPlain");
			return (Criteria) this;
		}

		public Criteria andTestPlainLessThanOrEqualTo(String value) {
			addCriterion("TEST_PLAIN <=", value, "testPlain");
			return (Criteria) this;
		}

		public Criteria andTestPlainLike(String value) {
			addCriterion("TEST_PLAIN like", value, "testPlain");
			return (Criteria) this;
		}

		public Criteria andTestPlainNotLike(String value) {
			addCriterion("TEST_PLAIN not like", value, "testPlain");
			return (Criteria) this;
		}

		public Criteria andTestPlainIn(List<String> values) {
			addCriterion("TEST_PLAIN in", values, "testPlain");
			return (Criteria) this;
		}

		public Criteria andTestPlainNotIn(List<String> values) {
			addCriterion("TEST_PLAIN not in", values, "testPlain");
			return (Criteria) this;
		}

		public Criteria andTestPlainBetween(String value1, String value2) {
			addCriterion("TEST_PLAIN between", value1, value2, "testPlain");
			return (Criteria) this;
		}

		public Criteria andTestPlainNotBetween(String value1, String value2) {
			addCriterion("TEST_PLAIN not between", value1, value2, "testPlain");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table test_chally
	 * @mbg.generated  Fri Jul 12 22:36:13 KST 2024
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table test_chally
     *
     * @mbg.generated do_not_delete_during_merge Fri Jul 12 22:30:49 KST 2024
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}