package com.chally.vo;

import java.util.Date;

public class UserInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.ID
     *
     * @mbg.generated Sun Jul 21 22:26:23 KST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.OAUTH_ID
     *
     * @mbg.generated Sun Jul 21 22:26:23 KST 2024
     */
    private String oauthId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.EMAIL
     *
     * @mbg.generated Sun Jul 21 22:26:23 KST 2024
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.NAME
     *
     * @mbg.generated Sun Jul 21 22:26:23 KST 2024
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.DELETE_AT
     *
     * @mbg.generated Sun Jul 21 22:26:23 KST 2024
     */
    private String deleteAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.REGIST_DT
     *
     * @mbg.generated Sun Jul 21 22:26:23 KST 2024
     */
    private Date registDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.UPDT_DT
     *
     * @mbg.generated Sun Jul 21 22:26:23 KST 2024
     */
    private Date updtDt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.ID
     *
     * @return the value of user_info.ID
     *
     * @mbg.generated Sun Jul 21 22:26:23 KST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.ID
     *
     * @param id the value for user_info.ID
     *
     * @mbg.generated Sun Jul 21 22:26:23 KST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.OAUTH_ID
     *
     * @return the value of user_info.OAUTH_ID
     *
     * @mbg.generated Sun Jul 21 22:26:23 KST 2024
     */
    public String getOauthId() {
        return oauthId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.OAUTH_ID
     *
     * @param oauthId the value for user_info.OAUTH_ID
     *
     * @mbg.generated Sun Jul 21 22:26:23 KST 2024
     */
    public void setOauthId(String oauthId) {
        this.oauthId = oauthId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.EMAIL
     *
     * @return the value of user_info.EMAIL
     *
     * @mbg.generated Sun Jul 21 22:26:23 KST 2024
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.EMAIL
     *
     * @param email the value for user_info.EMAIL
     *
     * @mbg.generated Sun Jul 21 22:26:23 KST 2024
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.NAME
     *
     * @return the value of user_info.NAME
     *
     * @mbg.generated Sun Jul 21 22:26:23 KST 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.NAME
     *
     * @param name the value for user_info.NAME
     *
     * @mbg.generated Sun Jul 21 22:26:23 KST 2024
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.DELETE_AT
     *
     * @return the value of user_info.DELETE_AT
     *
     * @mbg.generated Sun Jul 21 22:26:23 KST 2024
     */
    public String getDeleteAt() {
        return deleteAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.DELETE_AT
     *
     * @param deleteAt the value for user_info.DELETE_AT
     *
     * @mbg.generated Sun Jul 21 22:26:23 KST 2024
     */
    public void setDeleteAt(String deleteAt) {
        this.deleteAt = deleteAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.REGIST_DT
     *
     * @return the value of user_info.REGIST_DT
     *
     * @mbg.generated Sun Jul 21 22:26:23 KST 2024
     */
    public Date getRegistDt() {
        return registDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.REGIST_DT
     *
     * @param registDt the value for user_info.REGIST_DT
     *
     * @mbg.generated Sun Jul 21 22:26:23 KST 2024
     */
    public void setRegistDt(Date registDt) {
        this.registDt = registDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.UPDT_DT
     *
     * @return the value of user_info.UPDT_DT
     *
     * @mbg.generated Sun Jul 21 22:26:23 KST 2024
     */
    public Date getUpdtDt() {
        return updtDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.UPDT_DT
     *
     * @param updtDt the value for user_info.UPDT_DT
     *
     * @mbg.generated Sun Jul 21 22:26:23 KST 2024
     */
    public void setUpdtDt(Date updtDt) {
        this.updtDt = updtDt;
    }
}